apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1beta1
      name: backend
      kind: Ingress
    path: customTarget.json