apiVersion: v1
kind: Service
metadata:
  name: codestar-interchange-data-service
spec:
  type: LoadBalancer
  selector:
    app: codestar-interchange-data
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8081
