apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backend
spec:
  rules:
    - host: "$(INGRESS_HOST)"
      http:
        paths:
          - backend:
              serviceName: codestar-interchange-backend-service
              servicePort: 8080