apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backend
spec:
  rules:
    - host:  d1eb04041de9d8998c68e6985e17f6c8.sk1.eu-central-1.eks.amazonaws.com
      http:
        paths:
          - backend:
              serviceName: codestar-interchange-backend-service
              servicePort: 8080