name: build-and-test

on: [push]

jobs:
  shared:
    name: "shared / Build and test"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Gradle
      run: ./gradlew :shared:clean :shared:test

  backend:
    name: "backend / Build and test"
    needs: shared
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Gradle
      run: ./gradlew :backend:clean :backend:test

  frontend:
    name: "frontend / Build and test"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Run Yarn
      run: cd frontend && yarn && yarn build && yarn test

  data:
    name: "data / Build and test"
    needs: shared
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Gradle
      run: ./gradlew :data:clean :data:test



