name: deploy

on:
  push:
    branches:
      - dockerize-team-data

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: Azure/docker-login@v1
      with:
        login-server: 182176061631.dkr.ecr.eu-central-1.amazonaws.com
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build backend
      run: |
        cd backend
        ../gradlew build
        docker build -t codestar-interchange-backend .
        docker push 182176061631.dkr.ecr.eu-central-1.amazonaws.com/codestar-interchange-data:latest
    #- name: Deploy to Amazon
    #  run: echo "Deploying to Amazon... [PLACEHOLDER]"

