name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build containers
      run: echo "Building containers... [PLACEHOLDER]"
    - name: Deploy to Amazon
      run: echo "Deploying to Amazon... [PLACEHOLDER]"

